name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn run build

      - name: Unit test
        run: yarn run test:unit

      - name: Integration test
        run: yarn run test:integration

      - name: Publish to npm on main
        if: github.ref == 'refs/heads/main'
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            npm version patch
            npm publish
            git commit -am "[chore] Bump version"
            git push
            git push origin --tags
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}