name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: yarn

    - name: Run build
      run: yarn run build

    - name: Unit test
      run: yarn run test:unit

    - name: Integration test
      run: yarn run test:integration

    - name: Publish to npm on main
      if: github.ref == 'refs/heads/main'
      run: |
        npm version patch
        npm publish
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "[chore] Bump version"
        git push
        git push origin --tags
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
